# Generated by Django 6.0.7 on 2026-07-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_outboxevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(db_index=True)),
                ('event_type', models.CharField(max_length=255)),
                ('service_name', models.CharField(max_length=100)),
                ('correlation_id', models.CharField(db_index=True, max_length=255)),
                ('aggregate_type', models.CharField(max_length=50)),
                ('aggregate_id', models.CharField(max_length=255)),
                ('direction', models.CharField(choices=[('PUBLISHED', 'Published'), ('CONSUMED', 'Consumed')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'event_history',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['correlation_id', 'created_at'], name='event_histo_correla_c87777_idx'), models.Index(fields=['aggregate_type', 'aggregate_id'], name='event_histo_aggrega_102c3f_idx')],
            },
        ),
    ]
